/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiMentorRouteImport } from './routes/api/mentor'
import { Route as AuthenticatedRankingDetalhesRouteImport } from './routes/_authenticated/ranking-detalhes'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedPreview_niveisRouteImport } from './routes/_authenticated/preview_niveis'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNiveisRouteImport } from './routes/_authenticated/niveis'
import { Route as AuthenticatedMuralRouteImport } from './routes/_authenticated/mural'
import { Route as AuthenticatedLiderRouteImport } from './routes/_authenticated/lider'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedBemVindoRouteImport } from './routes/_authenticated/bem-vindo'
import { Route as AuthenticatedMensagensIndexRouteImport } from './routes/_authenticated/mensagens.index'
import { Route as AuthenticatedEstudosIndexRouteImport } from './routes/_authenticated/estudos.index'
import { Route as AuthenticatedPerfilUsernameRouteImport } from './routes/_authenticated/perfil_.$username'
import { Route as AuthenticatedModuloIdRouteImport } from './routes/_authenticated/modulo.$id'
import { Route as AuthenticatedMensagensNovoRouteImport } from './routes/_authenticated/mensagens.novo'
import { Route as AuthenticatedMensagensUsernameRouteImport } from './routes/_authenticated/mensagens.$username'
import { Route as AuthenticatedLicaoIdRouteImport } from './routes/_authenticated/licao.$id'
import { Route as AuthenticatedLicaoIdAprofundarRouteImport } from './routes/_authenticated/licao.$id_.aprofundar'
import { Route as AuthenticatedEstudosPlanoIdRouteImport } from './routes/_authenticated/estudos.plano.$id'
import { Route as AuthenticatedEstudosMeditacaoIdRouteImport } from './routes/_authenticated/estudos.meditacao.$id'
import { Route as AuthenticatedEstudosBiblicoIdRouteImport } from './routes/_authenticated/estudos.biblico.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorRoute = ApiMentorRouteImport.update({
  id: '/api/mentor',
  path: '/api/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRankingDetalhesRoute =
  AuthenticatedRankingDetalhesRouteImport.update({
    id: '/ranking-detalhes',
    path: '/ranking-detalhes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreview_niveisRoute =
  AuthenticatedPreview_niveisRouteImport.update({
    id: '/preview_niveis',
    path: '/preview_niveis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNiveisRoute = AuthenticatedNiveisRouteImport.update({
  id: '/niveis',
  path: '/niveis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMuralRoute = AuthenticatedMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiderRoute = AuthenticatedLiderRouteImport.update({
  id: '/lider',
  path: '/lider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBemVindoRoute = AuthenticatedBemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensIndexRoute =
  AuthenticatedMensagensIndexRouteImport.update({
    id: '/mensagens/',
    path: '/mensagens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudosIndexRoute =
  AuthenticatedEstudosIndexRouteImport.update({
    id: '/estudos/',
    path: '/estudos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilUsernameRoute =
  AuthenticatedPerfilUsernameRouteImport.update({
    id: '/perfil_/$username',
    path: '/perfil/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModuloIdRoute = AuthenticatedModuloIdRouteImport.update({
  id: '/modulo/$id',
  path: '/modulo/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensNovoRoute =
  AuthenticatedMensagensNovoRouteImport.update({
    id: '/mensagens/novo',
    path: '/mensagens/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensUsernameRoute =
  AuthenticatedMensagensUsernameRouteImport.update({
    id: '/mensagens/$username',
    path: '/mensagens/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLicaoIdRoute = AuthenticatedLicaoIdRouteImport.update({
  id: '/licao/$id',
  path: '/licao/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLicaoIdAprofundarRoute =
  AuthenticatedLicaoIdAprofundarRouteImport.update({
    id: '/licao/$id_/aprofundar',
    path: '/licao/$id/aprofundar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudosPlanoIdRoute =
  AuthenticatedEstudosPlanoIdRouteImport.update({
    id: '/estudos/plano/$id',
    path: '/estudos/plano/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudosMeditacaoIdRoute =
  AuthenticatedEstudosMeditacaoIdRouteImport.update({
    id: '/estudos/meditacao/$id',
    path: '/estudos/meditacao/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudosBiblicoIdRoute =
  AuthenticatedEstudosBiblicoIdRouteImport.update({
    id: '/estudos/biblico/$id',
    path: '/estudos/biblico/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/lider': typeof AuthenticatedLiderRoute
  '/mural': typeof AuthenticatedMuralRoute
  '/niveis': typeof AuthenticatedNiveisRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/preview_niveis': typeof AuthenticatedPreview_niveisRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/ranking-detalhes': typeof AuthenticatedRankingDetalhesRoute
  '/api/mentor': typeof ApiMentorRoute
  '/api/tts': typeof ApiTtsRoute
  '/licao/$id': typeof AuthenticatedLicaoIdRoute
  '/mensagens/$username': typeof AuthenticatedMensagensUsernameRoute
  '/mensagens/novo': typeof AuthenticatedMensagensNovoRoute
  '/modulo/$id': typeof AuthenticatedModuloIdRoute
  '/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
  '/estudos/': typeof AuthenticatedEstudosIndexRoute
  '/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/estudos/biblico/$id': typeof AuthenticatedEstudosBiblicoIdRoute
  '/estudos/meditacao/$id': typeof AuthenticatedEstudosMeditacaoIdRoute
  '/estudos/plano/$id': typeof AuthenticatedEstudosPlanoIdRoute
  '/licao/$id/aprofundar': typeof AuthenticatedLicaoIdAprofundarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/lider': typeof AuthenticatedLiderRoute
  '/mural': typeof AuthenticatedMuralRoute
  '/niveis': typeof AuthenticatedNiveisRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/preview_niveis': typeof AuthenticatedPreview_niveisRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/ranking-detalhes': typeof AuthenticatedRankingDetalhesRoute
  '/api/mentor': typeof ApiMentorRoute
  '/api/tts': typeof ApiTtsRoute
  '/licao/$id': typeof AuthenticatedLicaoIdRoute
  '/mensagens/$username': typeof AuthenticatedMensagensUsernameRoute
  '/mensagens/novo': typeof AuthenticatedMensagensNovoRoute
  '/modulo/$id': typeof AuthenticatedModuloIdRoute
  '/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
  '/estudos': typeof AuthenticatedEstudosIndexRoute
  '/mensagens': typeof AuthenticatedMensagensIndexRoute
  '/estudos/biblico/$id': typeof AuthenticatedEstudosBiblicoIdRoute
  '/estudos/meditacao/$id': typeof AuthenticatedEstudosMeditacaoIdRoute
  '/estudos/plano/$id': typeof AuthenticatedEstudosPlanoIdRoute
  '/licao/$id/aprofundar': typeof AuthenticatedLicaoIdAprofundarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/lider': typeof AuthenticatedLiderRoute
  '/_authenticated/mural': typeof AuthenticatedMuralRoute
  '/_authenticated/niveis': typeof AuthenticatedNiveisRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/preview_niveis': typeof AuthenticatedPreview_niveisRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/ranking-detalhes': typeof AuthenticatedRankingDetalhesRoute
  '/api/mentor': typeof ApiMentorRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/licao/$id': typeof AuthenticatedLicaoIdRoute
  '/_authenticated/mensagens/$username': typeof AuthenticatedMensagensUsernameRoute
  '/_authenticated/mensagens/novo': typeof AuthenticatedMensagensNovoRoute
  '/_authenticated/modulo/$id': typeof AuthenticatedModuloIdRoute
  '/_authenticated/perfil_/$username': typeof AuthenticatedPerfilUsernameRoute
  '/_authenticated/estudos/': typeof AuthenticatedEstudosIndexRoute
  '/_authenticated/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/_authenticated/estudos/biblico/$id': typeof AuthenticatedEstudosBiblicoIdRoute
  '/_authenticated/estudos/meditacao/$id': typeof AuthenticatedEstudosMeditacaoIdRoute
  '/_authenticated/estudos/plano/$id': typeof AuthenticatedEstudosPlanoIdRoute
  '/_authenticated/licao/$id_/aprofundar': typeof AuthenticatedLicaoIdAprofundarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bem-vindo'
    | '/home'
    | '/lider'
    | '/mural'
    | '/niveis'
    | '/perfil'
    | '/preview_niveis'
    | '/ranking'
    | '/ranking-detalhes'
    | '/api/mentor'
    | '/api/tts'
    | '/licao/$id'
    | '/mensagens/$username'
    | '/mensagens/novo'
    | '/modulo/$id'
    | '/perfil/$username'
    | '/estudos/'
    | '/mensagens/'
    | '/estudos/biblico/$id'
    | '/estudos/meditacao/$id'
    | '/estudos/plano/$id'
    | '/licao/$id/aprofundar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bem-vindo'
    | '/home'
    | '/lider'
    | '/mural'
    | '/niveis'
    | '/perfil'
    | '/preview_niveis'
    | '/ranking'
    | '/ranking-detalhes'
    | '/api/mentor'
    | '/api/tts'
    | '/licao/$id'
    | '/mensagens/$username'
    | '/mensagens/novo'
    | '/modulo/$id'
    | '/perfil/$username'
    | '/estudos'
    | '/mensagens'
    | '/estudos/biblico/$id'
    | '/estudos/meditacao/$id'
    | '/estudos/plano/$id'
    | '/licao/$id/aprofundar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bem-vindo'
    | '/_authenticated/home'
    | '/_authenticated/lider'
    | '/_authenticated/mural'
    | '/_authenticated/niveis'
    | '/_authenticated/perfil'
    | '/_authenticated/preview_niveis'
    | '/_authenticated/ranking'
    | '/_authenticated/ranking-detalhes'
    | '/api/mentor'
    | '/api/tts'
    | '/_authenticated/licao/$id'
    | '/_authenticated/mensagens/$username'
    | '/_authenticated/mensagens/novo'
    | '/_authenticated/modulo/$id'
    | '/_authenticated/perfil_/$username'
    | '/_authenticated/estudos/'
    | '/_authenticated/mensagens/'
    | '/_authenticated/estudos/biblico/$id'
    | '/_authenticated/estudos/meditacao/$id'
    | '/_authenticated/estudos/plano/$id'
    | '/_authenticated/licao/$id_/aprofundar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiMentorRoute: typeof ApiMentorRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor': {
      id: '/api/mentor'
      path: '/api/mentor'
      fullPath: '/api/mentor'
      preLoaderRoute: typeof ApiMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ranking-detalhes': {
      id: '/_authenticated/ranking-detalhes'
      path: '/ranking-detalhes'
      fullPath: '/ranking-detalhes'
      preLoaderRoute: typeof AuthenticatedRankingDetalhesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preview_niveis': {
      id: '/_authenticated/preview_niveis'
      path: '/preview_niveis'
      fullPath: '/preview_niveis'
      preLoaderRoute: typeof AuthenticatedPreview_niveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/niveis': {
      id: '/_authenticated/niveis'
      path: '/niveis'
      fullPath: '/niveis'
      preLoaderRoute: typeof AuthenticatedNiveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mural': {
      id: '/_authenticated/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof AuthenticatedMuralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lider': {
      id: '/_authenticated/lider'
      path: '/lider'
      fullPath: '/lider'
      preLoaderRoute: typeof AuthenticatedLiderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bem-vindo': {
      id: '/_authenticated/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof AuthenticatedBemVindoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/': {
      id: '/_authenticated/mensagens/'
      path: '/mensagens'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof AuthenticatedMensagensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos/': {
      id: '/_authenticated/estudos/'
      path: '/estudos'
      fullPath: '/estudos/'
      preLoaderRoute: typeof AuthenticatedEstudosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil_/$username': {
      id: '/_authenticated/perfil_/$username'
      path: '/perfil/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof AuthenticatedPerfilUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modulo/$id': {
      id: '/_authenticated/modulo/$id'
      path: '/modulo/$id'
      fullPath: '/modulo/$id'
      preLoaderRoute: typeof AuthenticatedModuloIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/novo': {
      id: '/_authenticated/mensagens/novo'
      path: '/mensagens/novo'
      fullPath: '/mensagens/novo'
      preLoaderRoute: typeof AuthenticatedMensagensNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/$username': {
      id: '/_authenticated/mensagens/$username'
      path: '/mensagens/$username'
      fullPath: '/mensagens/$username'
      preLoaderRoute: typeof AuthenticatedMensagensUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licao/$id': {
      id: '/_authenticated/licao/$id'
      path: '/licao/$id'
      fullPath: '/licao/$id'
      preLoaderRoute: typeof AuthenticatedLicaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licao/$id_/aprofundar': {
      id: '/_authenticated/licao/$id_/aprofundar'
      path: '/licao/$id/aprofundar'
      fullPath: '/licao/$id/aprofundar'
      preLoaderRoute: typeof AuthenticatedLicaoIdAprofundarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos/plano/$id': {
      id: '/_authenticated/estudos/plano/$id'
      path: '/estudos/plano/$id'
      fullPath: '/estudos/plano/$id'
      preLoaderRoute: typeof AuthenticatedEstudosPlanoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos/meditacao/$id': {
      id: '/_authenticated/estudos/meditacao/$id'
      path: '/estudos/meditacao/$id'
      fullPath: '/estudos/meditacao/$id'
      preLoaderRoute: typeof AuthenticatedEstudosMeditacaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos/biblico/$id': {
      id: '/_authenticated/estudos/biblico/$id'
      path: '/estudos/biblico/$id'
      fullPath: '/estudos/biblico/$id'
      preLoaderRoute: typeof AuthenticatedEstudosBiblicoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBemVindoRoute: typeof AuthenticatedBemVindoRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLiderRoute: typeof AuthenticatedLiderRoute
  AuthenticatedMuralRoute: typeof AuthenticatedMuralRoute
  AuthenticatedNiveisRoute: typeof AuthenticatedNiveisRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPreview_niveisRoute: typeof AuthenticatedPreview_niveisRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRankingDetalhesRoute: typeof AuthenticatedRankingDetalhesRoute
  AuthenticatedLicaoIdRoute: typeof AuthenticatedLicaoIdRoute
  AuthenticatedMensagensUsernameRoute: typeof AuthenticatedMensagensUsernameRoute
  AuthenticatedMensagensNovoRoute: typeof AuthenticatedMensagensNovoRoute
  AuthenticatedModuloIdRoute: typeof AuthenticatedModuloIdRoute
  AuthenticatedPerfilUsernameRoute: typeof AuthenticatedPerfilUsernameRoute
  AuthenticatedEstudosIndexRoute: typeof AuthenticatedEstudosIndexRoute
  AuthenticatedMensagensIndexRoute: typeof AuthenticatedMensagensIndexRoute
  AuthenticatedEstudosBiblicoIdRoute: typeof AuthenticatedEstudosBiblicoIdRoute
  AuthenticatedEstudosMeditacaoIdRoute: typeof AuthenticatedEstudosMeditacaoIdRoute
  AuthenticatedEstudosPlanoIdRoute: typeof AuthenticatedEstudosPlanoIdRoute
  AuthenticatedLicaoIdAprofundarRoute: typeof AuthenticatedLicaoIdAprofundarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBemVindoRoute: AuthenticatedBemVindoRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLiderRoute: AuthenticatedLiderRoute,
  AuthenticatedMuralRoute: AuthenticatedMuralRoute,
  AuthenticatedNiveisRoute: AuthenticatedNiveisRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPreview_niveisRoute: AuthenticatedPreview_niveisRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRankingDetalhesRoute: AuthenticatedRankingDetalhesRoute,
  AuthenticatedLicaoIdRoute: AuthenticatedLicaoIdRoute,
  AuthenticatedMensagensUsernameRoute: AuthenticatedMensagensUsernameRoute,
  AuthenticatedMensagensNovoRoute: AuthenticatedMensagensNovoRoute,
  AuthenticatedModuloIdRoute: AuthenticatedModuloIdRoute,
  AuthenticatedPerfilUsernameRoute: AuthenticatedPerfilUsernameRoute,
  AuthenticatedEstudosIndexRoute: AuthenticatedEstudosIndexRoute,
  AuthenticatedMensagensIndexRoute: AuthenticatedMensagensIndexRoute,
  AuthenticatedEstudosBiblicoIdRoute: AuthenticatedEstudosBiblicoIdRoute,
  AuthenticatedEstudosMeditacaoIdRoute: AuthenticatedEstudosMeditacaoIdRoute,
  AuthenticatedEstudosPlanoIdRoute: AuthenticatedEstudosPlanoIdRoute,
  AuthenticatedLicaoIdAprofundarRoute: AuthenticatedLicaoIdAprofundarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiMentorRoute: ApiMentorRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
