/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBemVindoRouteImport } from './routes/_authenticated/bem-vindo'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedJogosRouteImport } from './routes/_authenticated/jogos'
import { Route as AuthenticatedLiderRouteImport } from './routes/_authenticated/lider'
import { Route as AuthenticatedMuralRouteImport } from './routes/_authenticated/mural'
import { Route as AuthenticatedNiveisRouteImport } from './routes/_authenticated/niveis'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPreview_niveisRouteImport } from './routes/_authenticated/preview_niveis'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedRankingDetalhesRouteImport } from './routes/_authenticated/ranking-detalhes'
import { Route as AuthenticatedVersiculoRouteImport } from './routes/_authenticated/versiculo'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AuthenticatedAdminPregerarNarracaoRouteImport } from './routes/_authenticated/admin.pregerar-narracao'
import { Route as AuthenticatedAdminPregerarTextosRouteImport } from './routes/_authenticated/admin.pregerar-textos'
import { Route as AuthenticatedBibliaIndexRouteImport } from './routes/_authenticated/biblia.index'
import { Route as AuthenticatedBibliaTeologiaRouteImport } from './routes/_authenticated/biblia.teologia'
import { Route as AuthenticatedBibliaTeologiaModuleChapterRouteImport } from './routes/_authenticated/biblia.teologia.$module.$chapter'
import { Route as AuthenticatedBibliaMarcadosRouteImport } from './routes/_authenticated/biblia.marcados'
import { Route as AuthenticatedEstudosIndexRouteImport } from './routes/_authenticated/estudos.index'
import { Route as AuthenticatedJogosCruzadasRouteImport } from './routes/_authenticated/jogos.cruzadas'
import { Route as AuthenticatedJogosMilhaoRouteImport } from './routes/_authenticated/jogos.milhao'
import { Route as AuthenticatedJogosMultiplayerRouteImport } from './routes/_authenticated/jogos.multiplayer'
import { Route as AuthenticatedJogosPersonagemRouteImport } from './routes/_authenticated/jogos.personagem'
import { Route as AuthenticatedJogosRankingRouteImport } from './routes/_authenticated/jogos.ranking'
import { Route as AuthenticatedJogosVersiculoRouteImport } from './routes/_authenticated/jogos.versiculo'
import { Route as AuthenticatedLicaoIdRouteImport } from './routes/_authenticated/licao.$id'
import { Route as AuthenticatedLiderArvoreRouteImport } from './routes/_authenticated/lider_.arvore'
import { Route as AuthenticatedMensagensIndexRouteImport } from './routes/_authenticated/mensagens.index'
import { Route as AuthenticatedMensagensUsernameRouteImport } from './routes/_authenticated/mensagens.$username'
import { Route as AuthenticatedMensagensNovoRouteImport } from './routes/_authenticated/mensagens.novo'
import { Route as AuthenticatedModuloIdRouteImport } from './routes/_authenticated/modulo.$id'
import { Route as AuthenticatedNotasIndexRouteImport } from './routes/_authenticated/notas.index'
import { Route as AuthenticatedNotasIdRouteImport } from './routes/_authenticated/notas.$id'
import { Route as AuthenticatedPerfilUsernameRouteImport } from './routes/_authenticated/perfil_.$username'
import { Route as AuthenticatedBibliaBookChapterRouteImport } from './routes/_authenticated/biblia.$book.$chapter'
import { Route as AuthenticatedEstudosBiblicoIdRouteImport } from './routes/_authenticated/estudos.biblico.$id'
import { Route as AuthenticatedEstudosMeditacaoIdRouteImport } from './routes/_authenticated/estudos.meditacao.$id'
import { Route as AuthenticatedEstudosPlanoIdRouteImport } from './routes/_authenticated/estudos.plano.$id'
import { Route as AuthenticatedLicaoIdAprofundarRouteImport } from './routes/_authenticated/licao.$id_.aprofundar'
import { Route as AuthenticatedBibliaEstudoBookChapterVerseRouteImport } from './routes/_authenticated/biblia.estudo.$book.$chapter.$verse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBemVindoRoute = AuthenticatedBemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJogosRoute = AuthenticatedJogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiderRoute = AuthenticatedLiderRouteImport.update({
  id: '/lider',
  path: '/lider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMuralRoute = AuthenticatedMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNiveisRoute = AuthenticatedNiveisRouteImport.update({
  id: '/niveis',
  path: '/niveis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreview_niveisRoute =
  AuthenticatedPreview_niveisRouteImport.update({
    id: '/preview_niveis',
    path: '/preview_niveis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingDetalhesRoute =
  AuthenticatedRankingDetalhesRouteImport.update({
    id: '/ranking-detalhes',
    path: '/ranking-detalhes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVersiculoRoute = AuthenticatedVersiculoRouteImport.update({
  id: '/versiculo',
  path: '/versiculo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPregerarNarracaoRoute =
  AuthenticatedAdminPregerarNarracaoRouteImport.update({
    id: '/admin/pregerar-narracao',
    path: '/admin/pregerar-narracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPregerarTextosRoute =
  AuthenticatedAdminPregerarTextosRouteImport.update({
    id: '/admin/pregerar-textos',
    path: '/admin/pregerar-textos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliaIndexRoute =
  AuthenticatedBibliaIndexRouteImport.update({
    id: '/biblia/',
    path: '/biblia/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliaTeologiaRoute =
  AuthenticatedBibliaTeologiaRouteImport.update({
    id: '/biblia/teologia',
    path: '/biblia/teologia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliaTeologiaModuleChapterRoute =
  AuthenticatedBibliaTeologiaModuleChapterRouteImport.update({
    id: '/biblia/teologia/$module/$chapter',
    path: '/biblia/teologia/$module/$chapter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliaMarcadosRoute =
  AuthenticatedBibliaMarcadosRouteImport.update({
    id: '/biblia/marcados',
    path: '/biblia/marcados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudosIndexRoute =
  AuthenticatedEstudosIndexRouteImport.update({
    id: '/estudos/',
    path: '/estudos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJogosCruzadasRoute =
  AuthenticatedJogosCruzadasRouteImport.update({
    id: '/cruzadas',
    path: '/cruzadas',
    getParentRoute: () => AuthenticatedJogosRoute,
  } as any)
const AuthenticatedJogosMilhaoRoute =
  AuthenticatedJogosMilhaoRouteImport.update({
    id: '/milhao',
    path: '/milhao',
    getParentRoute: () => AuthenticatedJogosRoute,
  } as any)
const AuthenticatedJogosMultiplayerRoute =
  AuthenticatedJogosMultiplayerRouteImport.update({
    id: '/multiplayer',
    path: '/multiplayer',
    getParentRoute: () => AuthenticatedJogosRoute,
  } as any)
const AuthenticatedJogosPersonagemRoute =
  AuthenticatedJogosPersonagemRouteImport.update({
    id: '/personagem',
    path: '/personagem',
    getParentRoute: () => AuthenticatedJogosRoute,
  } as any)
const AuthenticatedJogosRankingRoute =
  AuthenticatedJogosRankingRouteImport.update({
    id: '/ranking',
    path: '/ranking',
    getParentRoute: () => AuthenticatedJogosRoute,
  } as any)
const AuthenticatedJogosVersiculoRoute =
  AuthenticatedJogosVersiculoRouteImport.update({
    id: '/versiculo',
    path: '/versiculo',
    getParentRoute: () => AuthenticatedJogosRoute,
  } as any)
const AuthenticatedLicaoIdRoute = AuthenticatedLicaoIdRouteImport.update({
  id: '/licao/$id',
  path: '/licao/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiderArvoreRoute =
  AuthenticatedLiderArvoreRouteImport.update({
    id: '/lider_/arvore',
    path: '/lider/arvore',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensIndexRoute =
  AuthenticatedMensagensIndexRouteImport.update({
    id: '/mensagens/',
    path: '/mensagens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensUsernameRoute =
  AuthenticatedMensagensUsernameRouteImport.update({
    id: '/mensagens/$username',
    path: '/mensagens/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensNovoRoute =
  AuthenticatedMensagensNovoRouteImport.update({
    id: '/mensagens/novo',
    path: '/mensagens/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModuloIdRoute = AuthenticatedModuloIdRouteImport.update({
  id: '/modulo/$id',
  path: '/modulo/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasIndexRoute = AuthenticatedNotasIndexRouteImport.update({
  id: '/notas/',
  path: '/notas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasIdRoute = AuthenticatedNotasIdRouteImport.update({
  id: '/notas/$id',
  path: '/notas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilUsernameRoute =
  AuthenticatedPerfilUsernameRouteImport.update({
    id: '/perfil_/$username',
    path: '/perfil/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliaBookChapterRoute =
  AuthenticatedBibliaBookChapterRouteImport.update({
    id: '/biblia/$book/$chapter',
    path: '/biblia/$book/$chapter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudosBiblicoIdRoute =
  AuthenticatedEstudosBiblicoIdRouteImport.update({
    id: '/estudos/biblico/$id',
    path: '/estudos/biblico/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudosMeditacaoIdRoute =
  AuthenticatedEstudosMeditacaoIdRouteImport.update({
    id: '/estudos/meditacao/$id',
    path: '/estudos/meditacao/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudosPlanoIdRoute =
  AuthenticatedEstudosPlanoIdRouteImport.update({
    id: '/estudos/plano/$id',
    path: '/estudos/plano/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLicaoIdAprofundarRoute =
  AuthenticatedLicaoIdAprofundarRouteImport.update({
    id: '/licao/$id_/aprofundar',
    path: '/licao/$id/aprofundar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliaEstudoBookChapterVerseRoute =
  AuthenticatedBibliaEstudoBookChapterVerseRouteImport.update({
    id: '/biblia/estudo/$book/$chapter/$verse',
    path: '/biblia/estudo/$book/$chapter/$verse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/jogos': typeof AuthenticatedJogosRouteWithChildren
  '/lider': typeof AuthenticatedLiderRoute
  '/mural': typeof AuthenticatedMuralRoute
  '/niveis': typeof AuthenticatedNiveisRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/preview_niveis': typeof AuthenticatedPreview_niveisRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/ranking-detalhes': typeof AuthenticatedRankingDetalhesRoute
  '/versiculo': typeof AuthenticatedVersiculoRoute
  '/api/tts': typeof ApiTtsRoute
  '/admin/pregerar-narracao': typeof AuthenticatedAdminPregerarNarracaoRoute
  '/admin/pregerar-textos': typeof AuthenticatedAdminPregerarTextosRoute
  '/biblia/marcados': typeof AuthenticatedBibliaMarcadosRoute
  '/biblia/teologia': typeof AuthenticatedBibliaTeologiaRoute
  '/biblia/teologia/$module/$chapter': typeof AuthenticatedBibliaTeologiaModuleChapterRoute
  '/jogos/cruzadas': typeof AuthenticatedJogosCruzadasRoute
  '/jogos/milhao': typeof AuthenticatedJogosMilhaoRoute
  '/jogos/multiplayer': typeof AuthenticatedJogosMultiplayerRoute
  '/jogos/personagem': typeof AuthenticatedJogosPersonagemRoute
  '/jogos/ranking': typeof AuthenticatedJogosRankingRoute
  '/jogos/versiculo': typeof AuthenticatedJogosVersiculoRoute
  '/licao/$id': typeof AuthenticatedLicaoIdRoute
  '/lider/arvore': typeof AuthenticatedLiderArvoreRoute
  '/mensagens/$username': typeof AuthenticatedMensagensUsernameRoute
  '/mensagens/novo': typeof AuthenticatedMensagensNovoRoute
  '/modulo/$id': typeof AuthenticatedModuloIdRoute
  '/notas/$id': typeof AuthenticatedNotasIdRoute
  '/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
  '/biblia/': typeof AuthenticatedBibliaIndexRoute
  '/estudos/': typeof AuthenticatedEstudosIndexRoute
  '/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/notas/': typeof AuthenticatedNotasIndexRoute
  '/biblia/$book/$chapter': typeof AuthenticatedBibliaBookChapterRoute
  '/estudos/biblico/$id': typeof AuthenticatedEstudosBiblicoIdRoute
  '/estudos/meditacao/$id': typeof AuthenticatedEstudosMeditacaoIdRoute
  '/estudos/plano/$id': typeof AuthenticatedEstudosPlanoIdRoute
  '/licao/$id/aprofundar': typeof AuthenticatedLicaoIdAprofundarRoute
  '/biblia/estudo/$book/$chapter/$verse': typeof AuthenticatedBibliaEstudoBookChapterVerseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/jogos': typeof AuthenticatedJogosRouteWithChildren
  '/lider': typeof AuthenticatedLiderRoute
  '/mural': typeof AuthenticatedMuralRoute
  '/niveis': typeof AuthenticatedNiveisRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/preview_niveis': typeof AuthenticatedPreview_niveisRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/ranking-detalhes': typeof AuthenticatedRankingDetalhesRoute
  '/versiculo': typeof AuthenticatedVersiculoRoute
  '/api/tts': typeof ApiTtsRoute
  '/admin/pregerar-narracao': typeof AuthenticatedAdminPregerarNarracaoRoute
  '/admin/pregerar-textos': typeof AuthenticatedAdminPregerarTextosRoute
  '/biblia/marcados': typeof AuthenticatedBibliaMarcadosRoute
  '/biblia/teologia': typeof AuthenticatedBibliaTeologiaRoute
  '/biblia/teologia/$module/$chapter': typeof AuthenticatedBibliaTeologiaModuleChapterRoute
  '/jogos/cruzadas': typeof AuthenticatedJogosCruzadasRoute
  '/jogos/milhao': typeof AuthenticatedJogosMilhaoRoute
  '/jogos/multiplayer': typeof AuthenticatedJogosMultiplayerRoute
  '/jogos/personagem': typeof AuthenticatedJogosPersonagemRoute
  '/jogos/ranking': typeof AuthenticatedJogosRankingRoute
  '/jogos/versiculo': typeof AuthenticatedJogosVersiculoRoute
  '/licao/$id': typeof AuthenticatedLicaoIdRoute
  '/lider/arvore': typeof AuthenticatedLiderArvoreRoute
  '/mensagens/$username': typeof AuthenticatedMensagensUsernameRoute
  '/mensagens/novo': typeof AuthenticatedMensagensNovoRoute
  '/modulo/$id': typeof AuthenticatedModuloIdRoute
  '/notas/$id': typeof AuthenticatedNotasIdRoute
  '/perfil/$username': typeof AuthenticatedPerfilUsernameRoute
  '/biblia': typeof AuthenticatedBibliaIndexRoute
  '/biblia/teologia': typeof AuthenticatedBibliaTeologiaRoute
  '/biblia/teologia/$module/$chapter': typeof AuthenticatedBibliaTeologiaModuleChapterRoute
  '/estudos': typeof AuthenticatedEstudosIndexRoute
  '/mensagens': typeof AuthenticatedMensagensIndexRoute
  '/notas': typeof AuthenticatedNotasIndexRoute
  '/biblia/$book/$chapter': typeof AuthenticatedBibliaBookChapterRoute
  '/estudos/biblico/$id': typeof AuthenticatedEstudosBiblicoIdRoute
  '/estudos/meditacao/$id': typeof AuthenticatedEstudosMeditacaoIdRoute
  '/estudos/plano/$id': typeof AuthenticatedEstudosPlanoIdRoute
  '/licao/$id/aprofundar': typeof AuthenticatedLicaoIdAprofundarRoute
  '/biblia/estudo/$book/$chapter/$verse': typeof AuthenticatedBibliaEstudoBookChapterVerseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/jogos': typeof AuthenticatedJogosRouteWithChildren
  '/_authenticated/lider': typeof AuthenticatedLiderRoute
  '/_authenticated/mural': typeof AuthenticatedMuralRoute
  '/_authenticated/niveis': typeof AuthenticatedNiveisRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/preview_niveis': typeof AuthenticatedPreview_niveisRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/ranking-detalhes': typeof AuthenticatedRankingDetalhesRoute
  '/_authenticated/versiculo': typeof AuthenticatedVersiculoRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/admin/pregerar-narracao': typeof AuthenticatedAdminPregerarNarracaoRoute
  '/_authenticated/admin/pregerar-textos': typeof AuthenticatedAdminPregerarTextosRoute
  '/_authenticated/biblia/marcados': typeof AuthenticatedBibliaMarcadosRoute
  '/_authenticated/biblia/teologia': typeof AuthenticatedBibliaTeologiaRoute
  '/_authenticated/jogos/cruzadas': typeof AuthenticatedJogosCruzadasRoute
  '/_authenticated/jogos/milhao': typeof AuthenticatedJogosMilhaoRoute
  '/_authenticated/jogos/multiplayer': typeof AuthenticatedJogosMultiplayerRoute
  '/_authenticated/jogos/personagem': typeof AuthenticatedJogosPersonagemRoute
  '/_authenticated/jogos/ranking': typeof AuthenticatedJogosRankingRoute
  '/_authenticated/jogos/versiculo': typeof AuthenticatedJogosVersiculoRoute
  '/_authenticated/licao/$id': typeof AuthenticatedLicaoIdRoute
  '/_authenticated/lider_/arvore': typeof AuthenticatedLiderArvoreRoute
  '/_authenticated/mensagens/$username': typeof AuthenticatedMensagensUsernameRoute
  '/_authenticated/mensagens/novo': typeof AuthenticatedMensagensNovoRoute
  '/_authenticated/modulo/$id': typeof AuthenticatedModuloIdRoute
  '/_authenticated/notas/$id': typeof AuthenticatedNotasIdRoute
  '/_authenticated/perfil_/$username': typeof AuthenticatedPerfilUsernameRoute
  '/_authenticated/biblia/': typeof AuthenticatedBibliaIndexRoute
  '/_authenticated/estudos/': typeof AuthenticatedEstudosIndexRoute
  '/_authenticated/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/_authenticated/notas/': typeof AuthenticatedNotasIndexRoute
  '/_authenticated/biblia/$book/$chapter': typeof AuthenticatedBibliaBookChapterRoute
  '/_authenticated/estudos/biblico/$id': typeof AuthenticatedEstudosBiblicoIdRoute
  '/_authenticated/estudos/meditacao/$id': typeof AuthenticatedEstudosMeditacaoIdRoute
  '/_authenticated/estudos/plano/$id': typeof AuthenticatedEstudosPlanoIdRoute
  '/_authenticated/licao/$id_/aprofundar': typeof AuthenticatedLicaoIdAprofundarRoute
  '/_authenticated/biblia/estudo/$book/$chapter/$verse': typeof AuthenticatedBibliaEstudoBookChapterVerseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bem-vindo'
    | '/home'
    | '/jogos'
    | '/lider'
    | '/mural'
    | '/niveis'
    | '/perfil'
    | '/preview_niveis'
    | '/ranking'
    | '/ranking-detalhes'
    | '/versiculo'
    | '/api/tts'
    | '/admin/pregerar-narracao'
    | '/admin/pregerar-textos'
    | '/biblia/marcados'
    | '/biblia/teologia'
    | '/biblia/teologia/$module/$chapter'
    | '/jogos/cruzadas'
    | '/jogos/milhao'
    | '/jogos/multiplayer'
    | '/jogos/personagem'
    | '/jogos/ranking'
    | '/jogos/versiculo'
    | '/licao/$id'
    | '/lider/arvore'
    | '/mensagens/$username'
    | '/mensagens/novo'
    | '/modulo/$id'
    | '/notas/$id'
    | '/perfil/$username'
    | '/biblia/'
    | '/estudos/'
    | '/mensagens/'
    | '/notas/'
    | '/biblia/$book/$chapter'
    | '/estudos/biblico/$id'
    | '/estudos/meditacao/$id'
    | '/estudos/plano/$id'
    | '/licao/$id/aprofundar'
    | '/biblia/estudo/$book/$chapter/$verse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bem-vindo'
    | '/home'
    | '/jogos'
    | '/lider'
    | '/mural'
    | '/niveis'
    | '/perfil'
    | '/preview_niveis'
    | '/ranking'
    | '/ranking-detalhes'
    | '/versiculo'
    | '/api/tts'
    | '/admin/pregerar-narracao'
    | '/admin/pregerar-textos'
    | '/biblia/marcados'
    | '/biblia/teologia'
    | '/biblia/teologia/$module/$chapter'
    | '/jogos/cruzadas'
    | '/jogos/milhao'
    | '/jogos/multiplayer'
    | '/jogos/personagem'
    | '/jogos/ranking'
    | '/jogos/versiculo'
    | '/licao/$id'
    | '/lider/arvore'
    | '/mensagens/$username'
    | '/mensagens/novo'
    | '/modulo/$id'
    | '/notas/$id'
    | '/perfil/$username'
    | '/biblia'
    | '/biblia/teologia'
    | '/biblia/teologia/$module/$chapter'
    | '/estudos'
    | '/mensagens'
    | '/notas'
    | '/biblia/$book/$chapter'
    | '/estudos/biblico/$id'
    | '/estudos/meditacao/$id'
    | '/estudos/plano/$id'
    | '/licao/$id/aprofundar'
    | '/biblia/estudo/$book/$chapter/$verse'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bem-vindo'
    | '/_authenticated/home'
    | '/_authenticated/jogos'
    | '/_authenticated/lider'
    | '/_authenticated/mural'
    | '/_authenticated/niveis'
    | '/_authenticated/perfil'
    | '/_authenticated/preview_niveis'
    | '/_authenticated/ranking'
    | '/_authenticated/ranking-detalhes'
    | '/_authenticated/versiculo'
    | '/api/tts'
    | '/_authenticated/admin/pregerar-narracao'
    | '/_authenticated/admin/pregerar-textos'
    | '/_authenticated/biblia/marcados'
    | '/_authenticated/biblia/teologia'
    | '/_authenticated/biblia/teologia/$module/$chapter'
    | '/_authenticated/jogos/cruzadas'
    | '/_authenticated/jogos/milhao'
    | '/_authenticated/jogos/multiplayer'
    | '/_authenticated/jogos/personagem'
    | '/_authenticated/jogos/ranking'
    | '/_authenticated/jogos/versiculo'
    | '/_authenticated/licao/$id'
    | '/_authenticated/lider_/arvore'
    | '/_authenticated/mensagens/$username'
    | '/_authenticated/mensagens/novo'
    | '/_authenticated/modulo/$id'
    | '/_authenticated/notas/$id'
    | '/_authenticated/perfil_/$username'
    | '/_authenticated/biblia/'
    | '/_authenticated/estudos/'
    | '/_authenticated/mensagens/'
    | '/_authenticated/notas/'
    | '/_authenticated/biblia/$book/$chapter'
    | '/_authenticated/estudos/biblico/$id'
    | '/_authenticated/estudos/meditacao/$id'
    | '/_authenticated/estudos/plano/$id'
    | '/_authenticated/licao/$id_/aprofundar'
    | '/_authenticated/biblia/estudo/$book/$chapter/$verse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bem-vindo': {
      id: '/_authenticated/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof AuthenticatedBemVindoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogos': {
      id: '/_authenticated/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof AuthenticatedJogosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lider': {
      id: '/_authenticated/lider'
      path: '/lider'
      fullPath: '/lider'
      preLoaderRoute: typeof AuthenticatedLiderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mural': {
      id: '/_authenticated/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof AuthenticatedMuralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/niveis': {
      id: '/_authenticated/niveis'
      path: '/niveis'
      fullPath: '/niveis'
      preLoaderRoute: typeof AuthenticatedNiveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preview_niveis': {
      id: '/_authenticated/preview_niveis'
      path: '/preview_niveis'
      fullPath: '/preview_niveis'
      preLoaderRoute: typeof AuthenticatedPreview_niveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking-detalhes': {
      id: '/_authenticated/ranking-detalhes'
      path: '/ranking-detalhes'
      fullPath: '/ranking-detalhes'
      preLoaderRoute: typeof AuthenticatedRankingDetalhesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/versiculo': {
      id: '/_authenticated/versiculo'
      path: '/versiculo'
      fullPath: '/versiculo'
      preLoaderRoute: typeof AuthenticatedVersiculoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/pregerar-narracao': {
      id: '/_authenticated/admin/pregerar-narracao'
      path: '/admin/pregerar-narracao'
      fullPath: '/admin/pregerar-narracao'
      preLoaderRoute: typeof AuthenticatedAdminPregerarNarracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pregerar-textos': {
      id: '/_authenticated/admin/pregerar-textos'
      path: '/admin/pregerar-textos'
      fullPath: '/admin/pregerar-textos'
      preLoaderRoute: typeof AuthenticatedAdminPregerarTextosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia/': {
      id: '/_authenticated/biblia/'
      path: '/biblia'
      fullPath: '/biblia/'
      preLoaderRoute: typeof AuthenticatedBibliaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia/teologia': {
      id: '/_authenticated/biblia/teologia'
      path: '/biblia/teologia'
      fullPath: '/biblia/teologia'
      preLoaderRoute: typeof AuthenticatedBibliaTeologiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia/teologia/$module/$chapter': {
      id: '/_authenticated/biblia/teologia/$module/$chapter'
      path: '/biblia/teologia/$module/$chapter'
      fullPath: '/biblia/teologia/$module/$chapter'
      preLoaderRoute: typeof AuthenticatedBibliaTeologiaModuleChapterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia/marcados': {
      id: '/_authenticated/biblia/marcados'
      path: '/biblia/marcados'
      fullPath: '/biblia/marcados'
      preLoaderRoute: typeof AuthenticatedBibliaMarcadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos/': {
      id: '/_authenticated/estudos/'
      path: '/estudos'
      fullPath: '/estudos/'
      preLoaderRoute: typeof AuthenticatedEstudosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jogos/cruzadas': {
      id: '/_authenticated/jogos/cruzadas'
      path: '/cruzadas'
      fullPath: '/jogos/cruzadas'
      preLoaderRoute: typeof AuthenticatedJogosCruzadasRouteImport
      parentRoute: typeof AuthenticatedJogosRoute
    }
    '/_authenticated/jogos/milhao': {
      id: '/_authenticated/jogos/milhao'
      path: '/milhao'
      fullPath: '/jogos/milhao'
      preLoaderRoute: typeof AuthenticatedJogosMilhaoRouteImport
      parentRoute: typeof AuthenticatedJogosRoute
    }
    '/_authenticated/jogos/multiplayer': {
      id: '/_authenticated/jogos/multiplayer'
      path: '/multiplayer'
      fullPath: '/jogos/multiplayer'
      preLoaderRoute: typeof AuthenticatedJogosMultiplayerRouteImport
      parentRoute: typeof AuthenticatedJogosRoute
    }
    '/_authenticated/jogos/personagem': {
      id: '/_authenticated/jogos/personagem'
      path: '/personagem'
      fullPath: '/jogos/personagem'
      preLoaderRoute: typeof AuthenticatedJogosPersonagemRouteImport
      parentRoute: typeof AuthenticatedJogosRoute
    }
    '/_authenticated/jogos/ranking': {
      id: '/_authenticated/jogos/ranking'
      path: '/ranking'
      fullPath: '/jogos/ranking'
      preLoaderRoute: typeof AuthenticatedJogosRankingRouteImport
      parentRoute: typeof AuthenticatedJogosRoute
    }
    '/_authenticated/jogos/versiculo': {
      id: '/_authenticated/jogos/versiculo'
      path: '/versiculo'
      fullPath: '/jogos/versiculo'
      preLoaderRoute: typeof AuthenticatedJogosVersiculoRouteImport
      parentRoute: typeof AuthenticatedJogosRoute
    }
    '/_authenticated/licao/$id': {
      id: '/_authenticated/licao/$id'
      path: '/licao/$id'
      fullPath: '/licao/$id'
      preLoaderRoute: typeof AuthenticatedLicaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lider_/arvore': {
      id: '/_authenticated/lider_/arvore'
      path: '/lider/arvore'
      fullPath: '/lider/arvore'
      preLoaderRoute: typeof AuthenticatedLiderArvoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/': {
      id: '/_authenticated/mensagens/'
      path: '/mensagens'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof AuthenticatedMensagensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/$username': {
      id: '/_authenticated/mensagens/$username'
      path: '/mensagens/$username'
      fullPath: '/mensagens/$username'
      preLoaderRoute: typeof AuthenticatedMensagensUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/novo': {
      id: '/_authenticated/mensagens/novo'
      path: '/mensagens/novo'
      fullPath: '/mensagens/novo'
      preLoaderRoute: typeof AuthenticatedMensagensNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modulo/$id': {
      id: '/_authenticated/modulo/$id'
      path: '/modulo/$id'
      fullPath: '/modulo/$id'
      preLoaderRoute: typeof AuthenticatedModuloIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas/': {
      id: '/_authenticated/notas/'
      path: '/notas'
      fullPath: '/notas/'
      preLoaderRoute: typeof AuthenticatedNotasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas/$id': {
      id: '/_authenticated/notas/$id'
      path: '/notas/$id'
      fullPath: '/notas/$id'
      preLoaderRoute: typeof AuthenticatedNotasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil_/$username': {
      id: '/_authenticated/perfil_/$username'
      path: '/perfil/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof AuthenticatedPerfilUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia/$book/$chapter': {
      id: '/_authenticated/biblia/$book/$chapter'
      path: '/biblia/$book/$chapter'
      fullPath: '/biblia/$book/$chapter'
      preLoaderRoute: typeof AuthenticatedBibliaBookChapterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos/biblico/$id': {
      id: '/_authenticated/estudos/biblico/$id'
      path: '/estudos/biblico/$id'
      fullPath: '/estudos/biblico/$id'
      preLoaderRoute: typeof AuthenticatedEstudosBiblicoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos/meditacao/$id': {
      id: '/_authenticated/estudos/meditacao/$id'
      path: '/estudos/meditacao/$id'
      fullPath: '/estudos/meditacao/$id'
      preLoaderRoute: typeof AuthenticatedEstudosMeditacaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos/plano/$id': {
      id: '/_authenticated/estudos/plano/$id'
      path: '/estudos/plano/$id'
      fullPath: '/estudos/plano/$id'
      preLoaderRoute: typeof AuthenticatedEstudosPlanoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licao/$id_/aprofundar': {
      id: '/_authenticated/licao/$id_/aprofundar'
      path: '/licao/$id/aprofundar'
      fullPath: '/licao/$id/aprofundar'
      preLoaderRoute: typeof AuthenticatedLicaoIdAprofundarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblia/estudo/$book/$chapter/$verse': {
      id: '/_authenticated/biblia/estudo/$book/$chapter/$verse'
      path: '/biblia/estudo/$book/$chapter/$verse'
      fullPath: '/biblia/estudo/$book/$chapter/$verse'
      preLoaderRoute: typeof AuthenticatedBibliaEstudoBookChapterVerseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedJogosRouteChildren {
  AuthenticatedJogosCruzadasRoute: typeof AuthenticatedJogosCruzadasRoute
  AuthenticatedJogosMilhaoRoute: typeof AuthenticatedJogosMilhaoRoute
  AuthenticatedJogosMultiplayerRoute: typeof AuthenticatedJogosMultiplayerRoute
  AuthenticatedJogosPersonagemRoute: typeof AuthenticatedJogosPersonagemRoute
  AuthenticatedJogosRankingRoute: typeof AuthenticatedJogosRankingRoute
  AuthenticatedJogosVersiculoRoute: typeof AuthenticatedJogosVersiculoRoute
}

const AuthenticatedJogosRouteChildren: AuthenticatedJogosRouteChildren = {
  AuthenticatedJogosCruzadasRoute: AuthenticatedJogosCruzadasRoute,
  AuthenticatedJogosMilhaoRoute: AuthenticatedJogosMilhaoRoute,
  AuthenticatedJogosMultiplayerRoute: AuthenticatedJogosMultiplayerRoute,
  AuthenticatedJogosPersonagemRoute: AuthenticatedJogosPersonagemRoute,
  AuthenticatedJogosRankingRoute: AuthenticatedJogosRankingRoute,
  AuthenticatedJogosVersiculoRoute: AuthenticatedJogosVersiculoRoute,
}

const AuthenticatedJogosRouteWithChildren =
  AuthenticatedJogosRoute._addFileChildren(AuthenticatedJogosRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBemVindoRoute: typeof AuthenticatedBemVindoRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJogosRoute: typeof AuthenticatedJogosRouteWithChildren
  AuthenticatedLiderRoute: typeof AuthenticatedLiderRoute
  AuthenticatedMuralRoute: typeof AuthenticatedMuralRoute
  AuthenticatedNiveisRoute: typeof AuthenticatedNiveisRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPreview_niveisRoute: typeof AuthenticatedPreview_niveisRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRankingDetalhesRoute: typeof AuthenticatedRankingDetalhesRoute
  AuthenticatedVersiculoRoute: typeof AuthenticatedVersiculoRoute
  AuthenticatedAdminPregerarNarracaoRoute: typeof AuthenticatedAdminPregerarNarracaoRoute
  AuthenticatedAdminPregerarTextosRoute: typeof AuthenticatedAdminPregerarTextosRoute
  AuthenticatedBibliaMarcadosRoute: typeof AuthenticatedBibliaMarcadosRoute
  AuthenticatedLicaoIdRoute: typeof AuthenticatedLicaoIdRoute
  AuthenticatedLiderArvoreRoute: typeof AuthenticatedLiderArvoreRoute
  AuthenticatedMensagensUsernameRoute: typeof AuthenticatedMensagensUsernameRoute
  AuthenticatedMensagensNovoRoute: typeof AuthenticatedMensagensNovoRoute
  AuthenticatedModuloIdRoute: typeof AuthenticatedModuloIdRoute
  AuthenticatedNotasIdRoute: typeof AuthenticatedNotasIdRoute
  AuthenticatedPerfilUsernameRoute: typeof AuthenticatedPerfilUsernameRoute
  AuthenticatedBibliaIndexRoute: typeof AuthenticatedBibliaIndexRoute
  AuthenticatedBibliaTeologiaRoute: typeof AuthenticatedBibliaTeologiaRoute
  AuthenticatedBibliaTeologiaModuleChapterRoute: typeof AuthenticatedBibliaTeologiaModuleChapterRoute
  AuthenticatedEstudosIndexRoute: typeof AuthenticatedEstudosIndexRoute
  AuthenticatedMensagensIndexRoute: typeof AuthenticatedMensagensIndexRoute
  AuthenticatedNotasIndexRoute: typeof AuthenticatedNotasIndexRoute
  AuthenticatedBibliaBookChapterRoute: typeof AuthenticatedBibliaBookChapterRoute
  AuthenticatedEstudosBiblicoIdRoute: typeof AuthenticatedEstudosBiblicoIdRoute
  AuthenticatedEstudosMeditacaoIdRoute: typeof AuthenticatedEstudosMeditacaoIdRoute
  AuthenticatedEstudosPlanoIdRoute: typeof AuthenticatedEstudosPlanoIdRoute
  AuthenticatedLicaoIdAprofundarRoute: typeof AuthenticatedLicaoIdAprofundarRoute
  AuthenticatedBibliaEstudoBookChapterVerseRoute: typeof AuthenticatedBibliaEstudoBookChapterVerseRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBemVindoRoute: AuthenticatedBemVindoRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJogosRoute: AuthenticatedJogosRouteWithChildren,
  AuthenticatedLiderRoute: AuthenticatedLiderRoute,
  AuthenticatedMuralRoute: AuthenticatedMuralRoute,
  AuthenticatedNiveisRoute: AuthenticatedNiveisRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPreview_niveisRoute: AuthenticatedPreview_niveisRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRankingDetalhesRoute: AuthenticatedRankingDetalhesRoute,
  AuthenticatedVersiculoRoute: AuthenticatedVersiculoRoute,
  AuthenticatedAdminPregerarNarracaoRoute:
    AuthenticatedAdminPregerarNarracaoRoute,
  AuthenticatedAdminPregerarTextosRoute: AuthenticatedAdminPregerarTextosRoute,
  AuthenticatedBibliaMarcadosRoute: AuthenticatedBibliaMarcadosRoute,
  AuthenticatedLicaoIdRoute: AuthenticatedLicaoIdRoute,
  AuthenticatedLiderArvoreRoute: AuthenticatedLiderArvoreRoute,
  AuthenticatedMensagensUsernameRoute: AuthenticatedMensagensUsernameRoute,
  AuthenticatedMensagensNovoRoute: AuthenticatedMensagensNovoRoute,
  AuthenticatedModuloIdRoute: AuthenticatedModuloIdRoute,
  AuthenticatedNotasIdRoute: AuthenticatedNotasIdRoute,
  AuthenticatedPerfilUsernameRoute: AuthenticatedPerfilUsernameRoute,
  AuthenticatedBibliaIndexRoute: AuthenticatedBibliaIndexRoute,
  AuthenticatedBibliaTeologiaRoute: AuthenticatedBibliaTeologiaRoute,
  AuthenticatedBibliaTeologiaModuleChapterRoute: AuthenticatedBibliaTeologiaModuleChapterRoute,
  AuthenticatedEstudosIndexRoute: AuthenticatedEstudosIndexRoute,
  AuthenticatedMensagensIndexRoute: AuthenticatedMensagensIndexRoute,
  AuthenticatedNotasIndexRoute: AuthenticatedNotasIndexRoute,
  AuthenticatedBibliaBookChapterRoute: AuthenticatedBibliaBookChapterRoute,
  AuthenticatedEstudosBiblicoIdRoute: AuthenticatedEstudosBiblicoIdRoute,
  AuthenticatedEstudosMeditacaoIdRoute: AuthenticatedEstudosMeditacaoIdRoute,
  AuthenticatedEstudosPlanoIdRoute: AuthenticatedEstudosPlanoIdRoute,
  AuthenticatedLicaoIdAprofundarRoute: AuthenticatedLicaoIdAprofundarRoute,
  AuthenticatedBibliaEstudoBookChapterVerseRoute:
    AuthenticatedBibliaEstudoBookChapterVerseRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
