-- Textos pré-escritos de compartilhamento — trilha Novo Convertido (10 lições)
INSERT INTO public.lesson_share_texts (lesson_id, lesson_title, share_text) VALUES
  ('db-1-2', 'Quem é Jesus?', 'Hoje parei diante de uma pergunta que o próprio Jesus fez aos discípulos: quem vocês dizem que eu sou? Não dá pra deixar essa resposta pela metade. Ou Jesus é só mais um bom professor de moral, ou ele é exatamente quem afirmou ser — Deus que se fez carne e habitou entre nós, antes mesmo de Abraão existir. C.S. Lewis dizia que essa segunda opção confortável, de admirar Jesus sem adorá-lo, simplesmente não existe pra quem lê os Evangelhos com honestidade. Essa não é uma pergunta acadêmica; é a mais pessoal que existe. Eu já respondi a minha, com Pedro: tu és o Cristo, o Filho do Deus vivo. E queria te convidar a responder a sua também, com calma e sinceridade.'),
  ('nc-1-1', 'O que aconteceu comigo?', 'Tem uma pergunta que talvez você já tenha se feito depois de virar cristão: o que exatamente aconteceu comigo? A Bíblia chama isso de novo nascimento — não uma versão melhorada de quem eu era, mas uma criação nova de verdade. Jesus disse a Nicodemos que era preciso nascer de novo, de cima, por obra do Espírito, não por esforço religioso. E Paulo confirma: quem está em Cristo é nova criação; as coisas antigas passaram. Isso não é discurso motivacional — é a realidade mais concreta que existe sobre quem eu sou agora diante de Deus. Se você também atravessou essa linha, comemore: o céu já se alegrou com isso antes de você mesmo entender direito o tamanho do que aconteceu.'),
  ('nc-1-2', 'Tenho certeza da salvação?', 'Já me perguntei: e se, no fim, eu descobrir que não era salvo de verdade? Descobri que essa dúvida não é sinal de fé fraca — muitas vezes é o oposto. A Bíblia diferencia ter salvação de ter certeza da salvação, e ensina que essa certeza vem de duas testemunhas: a Palavra escrita, que promete vida a quem crê no Filho, e o Espírito Santo, que testifica junto com o nosso espírito. Sentimentos oscilam de um dia pro outro; essas duas testemunhas não mudam. Aprendi que, quando a dúvida bate, o caminho não é discutir comigo mesmo, é voltar a essas duas testemunhas. Queria te contar isso porque talvez você também precise ouvir: a segurança da fé se constrói assim, não em sentir mais.'),
  ('nc-2-1', 'Por que ler a Bíblia todo dia?', 'Por que ler a Bíblia todo dia, se dá pra só ir aos cultos? Essa pergunta é mais honesta do que parece, e vale a pena responder de verdade. O salmista descreve a Palavra não como um holofote que ilumina o caminho inteiro, mas como uma lâmpada que ilumina só o próximo passo — por isso precisamos da luz de hoje, não da de daqui a um ano. E quando foi tentado no deserto, o próprio Jesus disse que não vivemos só de pão, mas de cada palavra que sai da boca de Deus. Comecei a separar dez minutos fixos por dia pra isso, começando pelo Evangelho de João, e o que mudou não foi volume de conhecimento — foi presença regular com Deus. Recomendo de coração.'),
  ('nc-2-2', 'Como orar quando não sei orar', 'Sabe aquele momento em que você quer orar e simplesmente não vêm as palavras? Isso é mais comum do que parece, até entre cristãos maduros — não é sinal de fé fraca. Jesus começou o Pai Nosso chamando Deus de ''Páter'', a palavra que uma criança usava pra chamar o próprio pai em casa. Ele não está impressionado com vocabulário difícil; está comovido por um coração de filho. E Paulo garante algo que me consolou muito: quando não sabemos orar, o próprio Espírito ora por nós, carregando o outro lado do peso. Isso mudou como eu oro. Se você também trava na hora de orar, tenta só falar como falaria com alguém que te ama profundamente — e, se faltar palavra, o silêncio diante de Deus já é oração.'),
  ('nc-3-1', 'O que é o Evangelho?', '''Evangelho'' virou uma palavra tão repetida que quase perdemos o impacto que ela deveria ter. No mundo antigo, ''euangelion'' era o anúncio oficial de que um novo rei havia nascido ou que uma guerra tinha sido vencida — não um conselho, uma notícia. Foi assim que entendi o que Jesus fez: morreu pelos meus pecados, foi sepultado e ressuscitou — fato histórico, não teoria religiosa. John Stott dizia que o Evangelho tem três tempos: no passado, Cristo morreu por nós; no presente, continua sendo poder de Deus pra sustentar quem crê; no futuro, aponta pro Reino que ainda vai vir em plenitude. Trouxe minha culpa mais antiga e coloquei do lado dessa notícia — e decidi confiar nela.'),
  ('nc-3-2', 'Graça e Adoção: chamado de filho', 'Existem várias imagens bíblicas para o que Deus fez na minha salvação, mas uma delas mudou como eu me enxergo: adoção. No mundo romano, um filho adotivo ganhava um novo nome, entrava numa nova linhagem e não podia ser deserdado. Paulo usa exatamente essa palavra, ''huiothesía'', pra descrever o que Deus fez comigo: ele não me deu só perdão, me deu um sobrenome. Agora posso chamá-lo de Pai, com o mesmo Espírito que confirma dentro de mim que essa palavra é verdadeira, não figura de linguagem. Comecei a orar chamando Deus assim, de propósito, mesmo quando soava estranho. Se você é filho adotivo de Deus também, vale a pena parar e deixar essa verdade te alcançar de novo hoje.'),
  ('nc-4-1', 'Igreja e Comunhão', 'Achei, por um tempo, que a vida cristã era um assunto só entre mim e Deus, e que igreja era complemento opcional. A Bíblia ensina o contrário: no instante em que nasci de novo, fui colocado dentro de um corpo — não existe, no Novo Testamento, a categoria de cristão sozinho. Em Atos 2, a marca dos primeiros convertidos não foi só fé pessoal, mas vida compartilhada: comunhão, ensino, oração e refeições juntos. E Hebreus não manda simplesmente não faltar às reuniões — conecta isso com um propósito: nos incentivarmos ao amor e às boas obras. Passei a procurar de verdade como as pessoas da minha igreja estão, não só presença física. Comunhão de verdade exige isso, e faz diferença na caminhada.'),
  ('nc-4-2', 'Batismo', 'Depois de crer em Cristo, o Novo Testamento espera um passo público e concreto: o batismo. Em Atos, isso acontece quase sempre no mesmo dia da conversão — o eunuco etíope, ao ver água no caminho, perguntou ''que me impede de ser batizado?'', porque já entendia isso como resposta natural à fé, não formalidade distante. Importante entender o que o batismo não é: ele não salva ninguém, a salvação é só pela graça, mediante a fé (Efésios 2:8-9). Ele é testemunho público de uma realidade que já aconteceu por dentro. Se você já creu e ainda não foi batizado, esse é o momento de conversar com seu pastor sobre os próximos passos. Se já foi, vale parar hoje e agradecer a Deus por esse dia.'),
  ('nc-4-3', 'Missão Inicial', 'Uma das primeiras coisas que Jesus fez com quem ele chamava era enviar essa pessoa pra contar pra outra. André, assim que encontrou o Messias, foi direto ao irmão Simão: achamos o Messias. Ele não esperou anos de maturidade teológica — a experiência recente já bastava pra um convite simples e honesto: vem e vê. Isso não significa que todo novo convertido precisa virar evangelista treinado da noite pro dia, mas mostra que ninguém precisa ''estar pronto'' pra contar o que Deus fez. Escrevi minha própria história — quem eu era antes, o que aconteceu, o que mudou — e procurei uma chance natural de contar pra alguém próximo. Se Cristo já mudou algo em você, sua história já é suficiente pra começar.')
ON CONFLICT (lesson_id) DO UPDATE SET
  lesson_title = EXCLUDED.lesson_title,
  share_text = EXCLUDED.share_text,
  updated_at = now();
