-- Reescrita dos textos de compartilhamento evangelístico (Módulo 1: Novo Convertido
-- e Módulo 2: Como Estudar a Bíblia). Substitui, via UPSERT, os 21 registros existentes
-- na tabela public.lesson_share_texts. Cada texto resume a lição, responde/complementa
-- a pergunta do título, e termina com referência bíblica ("De acordo com...").

-- Defensivo: a coluna updated_at deveria existir desde a migração original da tabela,
-- mas o ambiente cloud não a tem — cria agora se estiver faltando, sem dar erro se já existir.
ALTER TABLE public.lesson_share_texts
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

INSERT INTO public.lesson_share_texts (lesson_id, lesson_title, share_text) VALUES
  ('db-1-2', 'Quem é Jesus?', 'Acabei de concluir a lição "Quem é Jesus?" e entendi que essa não é uma pergunta qualquer — é a mais decisiva que existe. Jesus não deixou a opção de vê-lo apenas como bom mestre: ou é mentiroso, louco, ou exatamente quem afirmou ser, Deus encarnado. Ele é plenamente Deus e plenamente homem, o Verbo que estava com Deus e era Deus, e que se fez carne para habitar entre nós. Se Jesus é Deus, tudo o que ele disse tem autoridade sobre a minha vida, e a resposta certa diante dele não é admiração distante, mas fé e entrega. De acordo com João 1:1 e 1:14, o Verbo era Deus desde o princípio e se fez carne para viver entre nós.'),
  ('nc-1-1', 'O que aconteceu comigo?', 'Terminei a lição "O que aconteceu comigo?" e descobri que minha conversão não foi apenas uma decisão melhor — foi uma recriação feita por Deus. Jesus chamou isso de nascer de novo, "de novo" e "do alto" ao mesmo tempo: uma origem nova que só vem dele. Paulo chama a mesma realidade de nova criação, não uma versão melhorada do que eu era, mas algo qualitativamente diferente. As coisas antigas já passaram; eis que surgiram coisas novas. Se você também nasceu de novo, viva à altura dessa identidade; se ainda não, saiba que essa recriação está ao alcance de quem crê. De acordo com 2 Coríntios 5:17, se alguém está em Cristo, é nova criação.'),
  ('nc-1-2', 'Tenho certeza da salvação?', 'Concluí a lição "Tenho certeza da salvação?" e aprendi algo que trouxe descanso: a segurança da fé não nasce de sentimentos constantes, mas de duas testemunhas firmes. A primeira é a Palavra de Deus, que promete vida eterna a quem crê no Filho. A segunda é o próprio Espírito Santo, que testifica junto com a nossa consciência que somos filhos de Deus. Sentimentos oscilam de um dia para o outro; essas duas testemunhas, não. Quando a dúvida bater, o caminho não é discutir consigo mesmo, é voltar a elas. Se você crê em Jesus, pode saber — não apenas sentir — que tem vida eterna. De acordo com 1 João 5:13, essas coisas foram escritas para que saibamos que temos a vida eterna.'),
  ('nc-2-1', 'Por que ler a Bíblia todo dia?', 'Terminei a lição "Por que ler a Bíblia todo dia?" e entendi por que essa disciplina não é legalismo, mas necessidade real. A Palavra de Deus não é um holofote que ilumina o caminho inteiro de uma vez; é uma lâmpada que ilumina o próximo passo. Por isso preciso da luz de hoje, não apenas da de ontem. E quando foi tentado no deserto, o próprio Jesus afirmou que não vivemos só de pão, mas de cada palavra que sai da boca de Deus — alimento tão essencial quanto a comida. Sem essa Palavra diária, o homem interior enfraquece, mesmo que o exterior pareça forte. De acordo com Mateus 4:4, não só de pão viverá o homem, mas de toda palavra que procede da boca de Deus.'),
  ('nc-2-2', 'Como orar quando não sei orar', 'Concluí a lição "Como orar quando não sei orar" e recebi um alívio que talvez você também precise: não saber as palavras certas não é sinal de fé fraca. Jesus começou o Pai Nosso chamando Deus de "Pai" — a palavra que uma criança usava em casa. Ele não busca vocabulário difícil; busca um coração de filho. E quando as palavras faltam de verdade, o próprio Espírito Santo intercede por nós com gemidos que nem sabemos expressar, carregando o outro lado do peso junto conosco. Você nunca ora sozinho. Comece pequeno, fale como filho, e confie que o Espírito completa o que falta. De acordo com Romanos 8:26, o Espírito nos ajuda em nossa fraqueza e intercede por nós.'),
  ('nc-3-1', 'O que é o Evangelho?', 'Terminei a lição "O que é o Evangelho?" e reaprendi que essa palavra não é jargão religioso — é uma notícia. No mundo antigo, "evangelho" era o anúncio oficial de que um rei havia vencido uma guerra. É exatamente isso: Cristo morreu pelos nossos pecados, foi sepultado e ressuscitou ao terceiro dia, conforme as Escrituras — fato histórico, não teoria. Esse Evangelho tem três tempos: no passado, Cristo já morreu por nós; no presente, continua sendo poder de Deus para sustentar quem crê; no futuro, aponta para o Reino que ainda virá em plenitude. Não é só a porta de entrada da fé, é o ar que respiramos nela. De acordo com 1 Coríntios 15:3-4, Cristo morreu, foi sepultado e ressuscitou segundo as Escrituras.'),
  ('nc-3-2', 'Graça e Adoção: chamado de filho', 'Concluí a lição "Graça e Adoção" e entendi que Deus não me deu apenas perdão — me deu um sobrenome. No mundo antigo, o filho adotado ganhava um novo nome, entrava numa nova linhagem e jamais podia ser deserdado. É essa a palavra que Paulo escolhe para descrever o que Deus fez em mim: adoção. Agora posso chamá-lo de Pai, com o mesmo Espírito que confirma dentro de mim que essa palavra é real, não figura de linguagem. Se você também creu em Cristo, essa filiação já é sua — não pela sua performance, mas pela graça dele, que nos escolheu antes da fundação do mundo. De acordo com Efésios 1:5, Deus nos predestinou para sermos adotados como filhos por meio de Jesus Cristo.'),
  ('nc-4-1', 'Igreja e Comunhão', 'Terminei a lição "Igreja e Comunhão" e percebi um engano comum: achar que a vida cristã é só um assunto entre mim e Deus, e que a igreja é complemento opcional. A Bíblia ensina o contrário — no instante em que nasci de novo, fui colocado dentro de um corpo. Em Atos 2, a marca dos primeiros convertidos não foi apenas fé pessoal, mas vida compartilhada: comunhão, ensino, oração e mesa em conjunto. E a carta aos Hebreus não manda apenas não faltar às reuniões, mas se encontrar com um propósito: nos incentivarmos ao amor e às boas obras. Comunhão de verdade exige presença real, não apenas ida ocasional a um culto. De acordo com Atos 2:42, os primeiros cristãos perseveravam na comunhão, no partir do pão e nas orações.'),
  ('nc-4-2', 'Batismo', 'Concluí a lição "Batismo" e entendi por que o Novo Testamento trata esse passo como resposta natural e imediata à fé, não como formalidade distante. No livro de Atos, batismo e conversão quase sempre acontecem no mesmo dia — o eunuco etíope, ao ver água no caminho, perguntou: "que me impede de ser batizado?". É importante entender o que o batismo não é: ele não salva ninguém, a salvação é só pela graça, mediante a fé. Ele é o testemunho público de uma realidade que já aconteceu por dentro — identificação com a morte e ressurreição de Cristo. Se você já creu e ainda não foi batizado, converse com seu pastor sobre esse próximo passo. De acordo com Romanos 6:4, fomos sepultados com Cristo pelo batismo para andarmos em novidade de vida.'),
  ('nc-4-3', 'Missão Inicial', 'Terminei a lição "Missão Inicial" e vi um padrão simples se repetir: assim que André encontrou Jesus, foi direto contar ao seu irmão Simão. Ele não esperou anos de maturidade teológica — a experiência recente já bastava para um convite honesto: "vem e vê". Isso não significa que todo novo convertido precisa virar um evangelista treinado da noite para o dia, mas mostra que ninguém precisa "estar pronto" para contar o que Deus já fez. Se Cristo mudou algo em você, sua própria história já é suficiente para começar. Quem você pode chamar hoje para vir e ver o que você já viu? De acordo com João 1:41, André achou primeiro a seu irmão Simão e lhe disse: achamos o Messias.'),
  ('ceb-1-1', 'Autoridade e Inspiração das Escrituras', 'Concluí a lição "Autoridade e Inspiração das Escrituras" e entendi que dizer que a Bíblia é inspirada não significa apenas que ela é inspiradora, como um poema comovente. Significa que ela foi soprada por Deus mesmo — e por isso tem autoridade final sobre a igreja e sobre a minha vida. Nenhum comentário, tradição, sentimento ou experiência pode se sobrepor ao texto sagrado. Essa verdade me protege de dois extremos: do racionalismo, que só aceita o que a mente aprova, e do misticismo, que busca experiências e ignora o texto. Ler a Bíblia com essa reverência é sentar-se aos pés do próprio Deus. De acordo com 2 Timóteo 3:16, toda a Escritura é inspirada por Deus e útil para ensinar, corrigir e instruir em justiça.'),
  ('ceb-1-2', 'Contexto Histórico e Literário', 'Terminei a lição "Contexto Histórico e Literário" e aprendi uma frase que vou levar comigo: um texto sem contexto vira pretexto. A Bíblia é uma biblioteca de 66 livros, escritas em três línguas, ao longo de 1.500 anos, em gêneros diferentes — e ler poesia como manual técnico, ou parábola como reportagem, produz teologia deformada. Antes de perguntar "o que isso significa para mim?", preciso perguntar "o que isso significou para os primeiros ouvintes?". Só depois desse passo a aplicação pessoal fica segura, e não uma leitura forçada nas minhas próprias ideias. De acordo com Neemias 8:8, os levitas liam a Lei e explicavam o sentido, para que o povo entendesse a leitura.'),
  ('ceb-2-1', 'O Método Indutivo: Observar, Interpretar, Aplicar', 'Concluí a lição sobre o Método Indutivo — observar, interpretar, aplicar — e vi como a ordem certa muda tudo. Observar é ir devagar: notar repetições, conectores, contrastes, mudanças de tempo verbal. Interpretar é conectar: cruzar com outros textos, considerar o gênero, checar a intenção do autor. Aplicar é obedecer: descobrir o que Deus está pedindo e responder com a vida, não apenas com um "amém". Inverter essa ordem, aplicando antes de observar, é o atalho que empobrece a maioria dos devocionais. Esse método é, no fundo, uma disciplina de humildade diante do texto. De acordo com Atos 17:11, os bereanos examinavam diariamente as Escrituras para ver se aquilo que ouviam era verdade.'),
  ('ceb-2-2', 'Gêneros Literários: Lendo Cada Texto Como Ele Pede', 'Terminei a lição "Gêneros Literários" e entendi por que ler cada texto bíblico do mesmo jeito é um erro. Narrativa histórica normalmente descreve o que aconteceu, não necessariamente prescreve o que deve sempre acontecer. Poesia usa paralelismo e hipérbole — "meus olhos se consomem de chorar" não é diagnóstico médico, é linguagem de lamento. Lei precisa ser lida dentro da aliança, discernindo o permanente do cerimonial cumprido em Cristo. Sabedoria ensina padrões prováveis, não promessas garantidas. Ler a Bíblia bem começa por perguntar: que tipo de texto é este? De acordo com Marcos 4:33-34, Jesus falava por meio de muitas parábolas, conforme os discípulos podiam entender.'),
  ('ceb-3-1', 'Cristo, a Chave de Toda a Escritura', 'Concluí a lição "Cristo, a Chave de Toda a Escritura" e reaprendi o que Jesus ensinou aos discípulos de Emaús: toda a Bíblia fala dele. Não apenas os Evangelhos, mas Moisés, os Salmos e os Profetas também. Uma leitura da Bíblia sem Cristo produz duas doenças: moralismo, que trata a Bíblia como manual de bom comportamento, e legalismo, que a trata como código de regras para conquistar Deus. A leitura cristocêntrica cura as duas: a Lei revela minha incapacidade e me leva a Cristo, e a graça em Cristo me dá poder para viver o que a Lei descrevia. Cada personagem do Antigo Testamento encontra sentido pleno nele. De acordo com Lucas 24:27, Jesus explicou, começando por Moisés e os profetas, o que dizia dele em toda a Escritura.'),
  ('ceb-3-2', 'Hebraico e Grego: Ferramentas, Não Atalhos', 'Terminei a lição "Hebraico e Grego: Ferramentas, Não Atalhos" e aprendi um cuidado importante: conhecer as línguas originais ilumina o texto, mas também pode virar um truque perigoso quando usado sem responsabilidade. Muitos já ouviram um pregador dizer "no grego original isso significa..." para justificar quase qualquer coisa, tirando conclusões grandes de detalhes pequenos sem checar como o próprio autor usa a palavra em outros lugares. O significado de um termo é controlado pelo seu uso e contexto, não por uma curiosidade isolada de dicionário. Estudar as línguas originais é valioso quando feito com humildade e rigor, buscando aprovação diante de Deus. De acordo com 2 Timóteo 2:15, devemos manejar corretamente a palavra da verdade.'),
  ('ceb-4-1', 'Do Texto à Aplicação: Evitando os Erros Comuns', 'Concluí a lição "Do Texto à Aplicação" e entendi a aplicação como uma ponte com duas margens: de um lado, o mundo antigo do texto; do outro, o meu mundo hoje. A travessia só é segura quando primeiro identifico o princípio teológico que atravessa as duas margens — algo que não muda com a cultura — e só depois formulo como obedecer esse princípio no meu contexto específico. Um mandamento cultural carrega um princípio permanente que pode se expressar de formas diferentes hoje. Ignorar essa distinção produz tanto legalismo cultural quanto relativismo que descarta o texto. Ouvir a Palavra não basta; é preciso praticá-la. De acordo com Tiago 1:22, sede praticantes da palavra e não somente ouvintes, enganando a vocês mesmos.'),
  ('ceb-4-2', 'Interpretando Parábolas e Símbolos', 'Terminei a lição "Interpretando Parábolas e Símbolos" e vi como é fácil errar transformando cada detalhe de uma história em símbolo separado, mesmo quando o texto não sugere isso. A pergunta certa é sempre: qual é o ponto que esta parábola, no seu contexto original de pregação, estava fazendo? Da mesma forma, os símbolos apocalípticos quase sempre ecoam imagens já usadas em Daniel, Ezequiel ou Isaías — a Bíblia costuma interpretar a si mesma, e esse é o primeiro lugar para buscar resposta, antes de qualquer especulação externa. Jesus explicava tudo em particular aos seus discípulos, porque as parábolas exigem um coração disposto a entender. De acordo com Marcos 4:34, Jesus explicava tudo em particular aos seus próprios discípulos.'),
  ('ceb-4-3', 'Montando um Plano de Estudo Bíblico Pessoal', 'Concluí a lição "Montando um Plano de Estudo Bíblico Pessoal" e aprendi que a palavra hebraica por trás de "meditar" no Salmo 1 evoca um animal ruminando o alimento, mastigando devagar até extrair todo o proveito. Esse é o retrato de um estudo bíblico saudável: não é consumo rápido de informação, é rumina lenta da verdade até que ela alimente a alma inteira. E esse estudo pessoal nunca deve ficar isolado da igreja local — deságua nas perguntas feitas ao pastor, nas trocas no pequeno grupo, na correção fraterna que impede leituras equivocadas. Um plano simples e constante vale mais que picos de intensidade que não duram. De acordo com Salmos 1:2-3, bem-aventurado é aquele cujo prazer está na lei do Senhor e nela medita de dia e de noite.'),
  ('ceb-5-1', 'A Metanarrativa Bíblica: Uma História, Um Herói', 'Terminei a lição "A Metanarrativa Bíblica" e vi a Bíblia como um único drama em quatro atos. Criação: Deus faz um mundo bom e coloca o ser humano nele à sua imagem. Queda: Adão e Eva desobedecem, o pecado entra no mundo, e a comunhão com Deus se quebra — mas já ali Deus promete um descendente que esmagará a cabeça da serpente. Redenção: todo o Antigo Testamento prepara a vinda desse descendente, até que Jesus Cristo vive a vida perfeita, morre a morte que os pecadores deviam morrer e ressuscita. Restauração: a história caminha para a nova criação, onde Deus habitará com seu povo para sempre. Uma só história, um único herói. De acordo com Lucas 24:27, Jesus explicou, começando por Moisés e os profetas, o que dizia dele em toda a Escritura.'),
  ('ceb-5-2', 'Perguntas ao Texto: Aprendendo a Interrogar as Escrituras', 'Concluí a lição "Perguntas ao Texto" e entendi que bons leitores da Bíblia não são, antes de tudo, pessoas com muitas respostas — são pessoas que aprenderam a fazer boas perguntas ao texto. A primeira família de perguntas é de observação: o que o texto realmente diz, quem fala, para quem, quando, onde? A segunda é de contexto: quem escreveu, para qual comunidade, em qual momento da história? A terceira é teológica: o que este texto revela sobre o caráter de Deus e como se conecta com Cristo? Só depois vem a aplicação. Como Filipe perguntou ao etíope, a pergunta que também me faço é: entendo o que estou lendo? De acordo com Atos 8:30-31, Filipe perguntou: entendes o que estás lendo? E ele respondeu: e como poderei, se alguém não me ensinar?')
ON CONFLICT (lesson_id) DO UPDATE SET
  lesson_title = EXCLUDED.lesson_title,
  share_text = EXCLUDED.share_text,
  updated_at = now();
