-- Atualiza os 21 textos de compartilhamento (Módulo 1: Novo Convertido e
-- Módulo 2/3: Como Estudar a Bíblia) para terminarem com uma pergunta de
-- reflexão curta sobre o tema, além da referência bíblica "De acordo com...".

ALTER TABLE public.lesson_share_texts
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

INSERT INTO public.lesson_share_texts (lesson_id, lesson_title, share_text) VALUES
  ('db-1-2', 'Quem é Jesus?', 'Acabei de concluir a lição "Quem é Jesus?" e entendi que essa não é uma pergunta qualquer — é a mais decisiva que existe. Jesus não deixa a opção de vê-lo apenas como bom mestre: ou é mentiroso, louco, ou exatamente quem afirmou ser, Deus encarnado. Ele é plenamente Deus e plenamente homem, o Verbo que estava com Deus e era Deus, e que se fez carne para habitar entre nós. Se Jesus é Deus, tudo o que ele disse tem autoridade sobre a minha vida. De acordo com João 1:1,14, o Verbo era Deus desde o princípio e se fez carne para viver entre nós. E você, quem diz que Jesus é?'),
  ('nc-1-1', 'O que aconteceu comigo?', 'Terminei a lição "O que aconteceu comigo?" e descobri que minha conversão não foi uma decisão melhor — foi uma recriação feita por Deus. Jesus chamou isso de nascer de novo, "de novo" e "do alto" ao mesmo tempo. Paulo chama a mesma realidade de nova criação, não uma versão melhorada do que eu era, mas algo qualitativamente diferente. As coisas antigas já passaram; eis que surgiram coisas novas. De acordo com 2 Coríntios 5:17, se alguém está em Cristo, é nova criação. O que em você ainda precisa ser renovado por Deus?'),
  ('nc-1-2', 'Tenho certeza da salvação?', 'Concluí a lição "Tenho certeza da salvação?" e aprendi que a segurança da fé não nasce de sentimentos constantes, mas de duas testemunhas firmes: a Palavra de Deus, que promete vida eterna a quem crê no Filho, e o próprio Espírito Santo, que testifica junto com a nossa consciência que somos filhos de Deus. Sentimentos oscilam; essas testemunhas não. Quando a dúvida bater, volte a elas. De acordo com 1 João 5:13, isso foi escrito para que saibamos que temos a vida eterna. Sua certeza hoje descansa em sentimento ou na promessa de Deus?'),
  ('nc-2-1', 'Por que ler a Bíblia todo dia?', 'Terminei a lição "Por que ler a Bíblia todo dia?" e entendi por que essa disciplina não é legalismo, mas necessidade real. A Palavra não é um holofote que ilumina o caminho inteiro; é uma lâmpada que ilumina o próximo passo. Por isso preciso da luz de hoje, não só da de ontem. Jesus, tentado no deserto, disse que não vivemos só de pão, mas de cada palavra que sai da boca de Deus. De acordo com Mateus 4:4, o homem não viverá só de pão, mas de toda palavra de Deus. Que luz você precisa receber da Palavra hoje?'),
  ('nc-2-2', 'Como orar quando não sei orar', 'Concluí a lição "Como orar quando não sei orar" e recebi um alívio: não saber as palavras certas não é sinal de fé fraca. Jesus começou o Pai Nosso chamando Deus de "Pai" — a palavra que uma criança usava em casa. E quando as palavras faltam de verdade, o próprio Espírito Santo intercede por nós com gemidos que nem sabemos expressar. Você nunca ora sozinho. De acordo com Romanos 8:26, o Espírito nos ajuda em nossa fraqueza e intercede por nós. O que você ainda não colocou em palavras diante de Deus?'),
  ('nc-3-1', 'O que é o Evangelho?', 'Terminei a lição "O que é o Evangelho?" e reaprendi que essa palavra não é jargão religioso — é uma notícia. No mundo antigo, "evangelho" era o anúncio oficial de que um rei havia vencido uma guerra. É isso: Cristo morreu pelos nossos pecados, foi sepultado e ressuscitou ao terceiro dia, conforme as Escrituras — fato histórico, não teoria. Não é só a porta de entrada da fé, é o ar que respiramos nela. De acordo com 1 Coríntios 15:3-4, Cristo morreu, foi sepultado e ressuscitou segundo as Escrituras. Essa notícia já mudou de verdade como você vive?'),
  ('nc-3-2', 'Graça e Adoção: chamado de filho', 'Concluí a lição "Graça e Adoção" e entendi que Deus não me deu apenas perdão — me deu um sobrenome. No mundo antigo, o filho adotado ganhava um novo nome, entrava numa nova linhagem e jamais podia ser deserdado. É essa a palavra que Paulo escolhe: adoção. Agora posso chamá-lo de Pai, com o mesmo Espírito que confirma isso dentro de mim. De acordo com Efésios 1:5, Deus nos predestinou para sermos adotados como filhos por meio de Jesus Cristo. Você tem vivido como filho amado, ou ainda como órfão?'),
  ('nc-4-1', 'Igreja e Comunhão', 'Terminei a lição "Igreja e Comunhão" e percebi um engano comum: achar que a vida cristã é só um assunto entre mim e Deus, e que a igreja é complemento opcional. A Bíblia ensina o contrário — no instante em que nasci de novo, fui colocado dentro de um corpo. Em Atos 2, a marca dos primeiros convertidos foi vida compartilhada: comunhão, ensino, oração e mesa em conjunto. De acordo com Atos 2:42, os primeiros cristãos perseveravam na comunhão, no partir do pão e nas orações. Quem está cuidando de você — e de quem você está cuidando?'),
  ('nc-4-2', 'Batismo', 'Concluí a lição "Batismo" e entendi por que o Novo Testamento trata esse passo como resposta natural e imediata à fé. No livro de Atos, batismo e conversão quase sempre acontecem no mesmo dia — o eunuco etíope, ao ver água no caminho, perguntou: "que me impede de ser batizado?". O batismo não salva ninguém, a salvação é só pela graça, mediante a fé; ele é o testemunho público de uma realidade que já aconteceu por dentro. De acordo com Romanos 6:4, fomos sepultados com Cristo pelo batismo para andarmos em novidade de vida. O que ainda te impede de dar esse passo?'),
  ('nc-4-3', 'Missão Inicial', 'Terminei a lição "Missão Inicial" e vi um padrão simples: assim que André encontrou Jesus, foi direto contar ao seu irmão Simão. Ele não esperou anos de maturidade teológica — a experiência recente já bastava para um convite honesto: "vem e vê". Ninguém precisa "estar pronto" para contar o que Deus já fez. Se Cristo mudou algo em você, sua própria história já é suficiente para começar. De acordo com João 1:41, André achou primeiro a seu irmão Simão e lhe disse: achamos o Messias. Quem você pode convidar hoje para vir e ver?'),
  ('ceb-1-1', 'Autoridade e Inspiração das Escrituras', 'Concluí a lição "Autoridade e Inspiração das Escrituras" e entendi que dizer que a Bíblia é inspirada não significa apenas que ela é inspiradora, como um poema. Significa que ela foi soprada por Deus mesmo — e por isso tem autoridade final sobre a igreja e sobre a minha vida. Nenhum comentário, tradição ou sentimento pode se sobrepor ao texto sagrado. De acordo com 2 Timóteo 3:16, toda a Escritura é inspirada por Deus e útil para ensinar, corrigir e instruir em justiça. Você lê a Bíblia como palavra de Deus, ou como um livro qualquer?'),
  ('ceb-1-2', 'Contexto Histórico e Literário', 'Terminei a lição "Contexto Histórico e Literário" e aprendi uma frase que vou levar comigo: um texto sem contexto vira pretexto. A Bíblia é uma biblioteca de 66 livros, escrita em três línguas, ao longo de 1.500 anos, em gêneros diferentes — e ler poesia como manual técnico, ou parábola como reportagem, produz teologia deformada. De acordo com Neemias 8:8, os levitas liam a Lei e explicavam o sentido, para que o povo entendesse. Você já perguntou o que o texto significou antes de perguntar o que ele significa pra você?'),
  ('ceb-2-1', 'O Método Indutivo: Observar, Interpretar, Aplicar', 'Concluí a lição sobre o Método Indutivo — observar, interpretar, aplicar — e vi como a ordem certa muda tudo. Observar é ir devagar: notar repetições, conectores, contrastes. Interpretar é conectar: cruzar com outros textos, considerar o gênero. Aplicar é obedecer: descobrir o que Deus pede e responder com a vida, não só com um "amém". De acordo com Atos 17:11, os bereanos examinavam diariamente as Escrituras para ver se aquilo que ouviam era verdade. Você tem parado tempo suficiente diante do texto antes de aplicá-lo?'),
  ('ceb-2-2', 'Gêneros Literários: Lendo Cada Texto Como Ele Pede', 'Terminei a lição "Gêneros Literários" e entendi por que ler cada texto bíblico do mesmo jeito é um erro. Narrativa histórica normalmente descreve o que aconteceu, não necessariamente prescreve o que deve sempre acontecer. Poesia usa paralelismo e hipérbole — "meus olhos se consomem de chorar" é linguagem de lamento, não diagnóstico médico. Lei precisa ser lida dentro da aliança. De acordo com Marcos 4:33-34, Jesus falava por meio de parábolas, conforme os discípulos podiam entender. Você já leu poesia como lei, ou lei como poesia?'),
  ('ceb-3-1', 'Cristo, a Chave de Toda a Escritura', 'Concluí a lição "Cristo, a Chave de Toda a Escritura" e reaprendi o que Jesus ensinou aos discípulos de Emaús: toda a Bíblia fala dele — não só os Evangelhos, mas Moisés, os Salmos e os Profetas também. Uma leitura sem Cristo produz moralismo (manual de bom comportamento) ou legalismo (regras para conquistar Deus). A leitura cristocêntrica cura as duas. De acordo com Lucas 24:27, Jesus explicou, começando por Moisés e os profetas, o que dizia dele em toda a Escritura. Você encontrou Cristo no que leu hoje?'),
  ('ceb-3-2', 'Hebraico e Grego: Ferramentas, Não Atalhos', 'Terminei a lição "Hebraico e Grego: Ferramentas, Não Atalhos" e aprendi um cuidado importante: conhecer as línguas originais ilumina o texto, mas pode virar um truque perigoso quando usado sem responsabilidade, tirando conclusões grandes de detalhes pequenos sem checar o uso do autor em outros lugares. O significado de um termo é controlado pelo seu uso e contexto. De acordo com 2 Timóteo 2:15, devemos manejar corretamente a palavra da verdade. Você busca as línguas originais por humildade, ou pra impressionar?'),
  ('ceb-4-1', 'Do Texto à Aplicação: Evitando os Erros Comuns', 'Concluí a lição "Do Texto à Aplicação" e entendi a aplicação como uma ponte com duas margens: o mundo antigo do texto e o meu mundo hoje. A travessia só é segura quando primeiro identifico o princípio teológico que atravessa as duas margens — algo que não muda com a cultura — e só depois formulo como obedecê-lo hoje. Ouvir a Palavra não basta; é preciso praticá-la. De acordo com Tiago 1:22, sede praticantes da palavra e não somente ouvintes, enganando a vocês mesmos. Que princípio permanente você ainda não aplicou na sua vida?'),
  ('ceb-4-2', 'Interpretando Parábolas e Símbolos', 'Terminei a lição "Interpretando Parábolas e Símbolos" e vi como é fácil errar transformando cada detalhe de uma história em símbolo separado, mesmo quando o texto não sugere isso. A pergunta certa é sempre: qual é o ponto que esta parábola, no seu contexto original, estava fazendo? Os símbolos apocalípticos quase sempre ecoam imagens já usadas em Daniel, Ezequiel ou Isaías. De acordo com Marcos 4:34, Jesus explicava tudo em particular aos seus próprios discípulos. Você já buscou o ponto original da parábola, antes de criar o seu?'),
  ('ceb-4-3', 'Montando um Plano de Estudo Bíblico Pessoal', 'Concluí a lição "Montando um Plano de Estudo Bíblico Pessoal" e aprendi que "meditar" no Salmo 1 evoca um animal ruminando o alimento, mastigando devagar até extrair todo o proveito. Esse é o retrato de um estudo bíblico saudável: não é consumo rápido de informação. E esse estudo nunca deve ficar isolado da igreja local — deságua nas perguntas ao pastor, nas trocas no pequeno grupo. De acordo com Salmos 1:2, bem-aventurado é aquele cujo prazer está na lei do Senhor. Seu estudo bíblico tem te levado de volta à igreja, ou te isolado dela?'),
  ('ceb-5-1', 'A Metanarrativa Bíblica: Uma História, Um Herói', 'Terminei a lição "A Metanarrativa Bíblica" e vi a Bíblia como um único drama em quatro atos. Criação: Deus faz um mundo bom. Queda: o pecado entra e a comunhão com Deus se quebra — mas já ali Deus promete um descendente que esmagará a cabeça da serpente. Redenção: Jesus vive a vida perfeita, morre a morte que os pecadores deviam morrer e ressuscita. Restauração: a nova criação vem. De acordo com Lucas 24:27, Jesus explicou, começando por Moisés e os profetas, o que dizia dele em toda a Escritura. Você já se enxergou dentro dessa história, ou só a lê de fora?'),
  ('ceb-5-2', 'Perguntas ao Texto: Aprendendo a Interrogar as Escrituras', 'Concluí a lição "Perguntas ao Texto" e entendi que bons leitores da Bíblia não são, antes de tudo, pessoas com muitas respostas — são pessoas que aprenderam a fazer boas perguntas. Observação: o que o texto realmente diz? Contexto: quem escreveu, para quem, quando? Teológica: o que revela sobre Deus e como se conecta com Cristo? Só depois vem a aplicação. De acordo com Atos 8:30-31, Filipe perguntou ao etíope: entendes o que estás lendo? E ele respondeu: como poderia, se ninguém me ensina? Você entende o que está lendo?')
ON CONFLICT (lesson_id) DO UPDATE SET
  lesson_title = EXCLUDED.lesson_title,
  share_text = EXCLUDED.share_text,
  updated_at = now();
